### ISSUE TITLE
feat: chatGPT apiを導入して対話機能を実装する。

### ISSUE THREAD

**Issue by QwerTayu** [hengin-eer/bocchi-talk#18]
### 要望の概要

対話機能を作ろう

### 要望の動機

8/15くらいまでには作りたい

### 要望の提案

- [ ] ChatGPT APIの利用初期設定
- [ ] APIの読み込み
- [ ] メッセの表示？

**Comment by hengin-eer** [comment]
Open AIのnodeモジュールあるみたいやし意外とすぐにできそう
以下の記事が参考になる
[ChatGPT APIとNext.jsでお手軽チャットアプリ作成 - Zenn](https://zenn.dev/rorisutarou/articles/6f21450ea34cc3)

**Comment by hengin-eer** [comment]
> あとのスタイリングは頼んます @hengin-eer 

🙄🙄🙄

**Comment by hengin-eer** [comment]
実装できたので閉じます～
