### ISSUE TITLE
Bug: スマホでキーボードを展開したときにChat画面が縮小しないバグ

### ISSUE THREAD

**Issue by QwerTayu** [hengin-eer/bocchi-talk#24]
### バグの概要

スマホ等で仮想キーボード展開時に、chat画面がキーボード展開スペースに合わせて縮小しないバグを直したい

### バグの再現手順

1. スマホでPWAを立ち上げ
2. Chatで入力欄をタップ→キーボードが展開する
![Record_2023-08-13-14-35-30](https://github.com/hengin-eer/bocchi-talk/assets/114202555/30460a03-c537-4c9d-8ba0-5ba6fbb103c5)

### 期待する動作

キーボードが展開したのに合わせてChat画面のheightが縮小して表示される

### 実際の動作

Chat画面の上部もしくは下部が隠れて見えなくなる

**Comment by QwerTayu** [comment]
https://ginpen.com/2023/08/08/update-height-by-keyboard-open-using-visual-viewport/

**Comment by QwerTayu** [comment]
これ #18 の最中に、visualViewportを設定したことで治ったんじゃないかなぁ、、、
vercelにデプロイしてスマホで試してみて確認ですね

**Comment by hengin-eer** [comment]
解決してるっぽいのでClose～
