### ISSUE TITLE
feat: トップページの追加

### ISSUE THREAD

**Issue by QwerTayu** [hengin-eer/bocchi-talk#26]
### 要望の概要

機能紹介やログインリンクなどが存在するトップページ（プロモーションページ）を追加したい

### 要望の動機

それっぽくするため

### 要望の提案

- [ ] index.jsをトップページとして編集
  - [ ] ダミーのログインリンクを追加
  - [ ] アプリの紹介欄

**Comment by hengin-eer** [comment]
@QwerTayu ちょいまち #23 に作ってある

**Comment by hengin-eer** [comment]
#23 を参照の程～
