### ISSUE TITLE
feat: ChatGPTとの対話機能を実装する。

### ISSUE THREAD

**Issue by QwerTayu** [hengin-eer/bocchi-talk#28]
### 要望の概要

ChatGPTと話せるようにしよう

### 要望の動機

8/18の進捗報告会までに実装したい。
これを実装しないと始まらない...

### 要望の提案

- [ ] ChatGPT apiの実装方法を調べる
- [ ] ChatGPTのapiを使用できるように申請
- [ ] apiを読み込み
- [ ] 表示させる
- [ ] 実装

@hengin-eer 適当です...詳しくおなしゃす

**Comment by hengin-eer** [comment]
これも #18 で立ててるでい

**Comment by hengin-eer** [comment]
てことで👋
