### ISSUE TITLE
辞書機能

### ISSUE THREAD

**Issue by hengin-eer** [hengin-eer/bocchi-talk#40]
## 要望する機能

- チャットを右クリックしたときに表示されるナビゲーションより操作
- ただし現状チャットの文章を丸ごと選択している状態のため、単語ごとに選ぶ必要がある
- 案1
  - 単語を選択した状態で右クリック
  - ナビゲーションの辞書から選択した単語の意味を調べる
- 案2
  - 右クリックで辞書を選択する
  - ポップアップが表示される
  - ポップアップ内で文章が単語ごとにマーキングされて表示される
  - 単語をタップすると辞書によってその単語を調べられる

## 実装方法について

- [WordsAPI](https://www.wordsapi.com/)を使用する
- 1日当たり、2500回までリクエストできるらしい
- WordsAPIを使用してアプリ内で辞書を引くか、Weblioなどのサイトの該当単語のページに飛ばすか

**Comment by QwerTayu** [comment]
- [ ] 右クリックメニューから使用できるようにする
- [ ] ChatGPT以外の良い方法があればそれを使いたい...
