### ISSUE TITLE
Bug: ChatGPTの応答が来る前に文字を入力していると、応答が来た際に入力内容が消えてしまう

### ISSUE THREAD

**Issue by QwerTayu** [hengin-eer/bocchi-talk#42]
### バグの概要

ChatGPTの応答が来る前に文字を入力していると、応答が来た際に入力内容が消えてしまうバグ

### バグの再現手順

1. なにかチャットを送ります。
2. ChatGPTの返信が来る前にチャット入力欄にテキストを入力します。
3. ChatGPTの返信が返ってきたときに、入力内容が消えてしまいます。

### 期待する動作

ChatGPTの応答があってもそれ以前に入力欄に入力していた文字は記憶されていてほしい

### 実際の動作

これは、バグではないのかもしれない。

**Comment by hengin-eer** [comment]
@QwerTayu おけえ
今作業中のブランチで同時に修正しちゃうわ

**Comment by hengin-eer** [comment]
確認出来たらこのIssueを閉じちゃってね

**Comment by QwerTayu** [comment]
確認しました～
