### ISSUE TITLE
feat: チャットタイトルを編集できるようにしたい

### ISSUE THREAD

**Issue by hengin-eer** [hengin-eer/bocchi-talk#55]
### 要望の概要

各チャットでタイトルを編集できるようにしたい

### 要望の動機

現状チャットタイトルは編集できず、ダッシュボードに表示されるチャットタイトルは、アクセスしたURLに依存している。
（例えば`/chat/chat1`にアクセスしてチャットを行い、ダッシュボートからチャット履歴を閲覧すると、チャットタイトル: chat1となっている。）

### 要望の提案

- [x] チャットタイトルを編集可能にする
- [x] チャットタイトルをデータベースに保存する
- [x] チャットタイトルが変更されると、データベースの値も更新する

## 参考
- [Editable \- Chakra UI](https://chakra-ui.com/docs/components/editable/usage)

**Comment by QwerTayu** [comment]
データベースと連携した後の編集方法だけど、ヘッダーのタイトルを直接編集するんじゃなくて、sidemenuに編集するところ作れば良さそう
