### ISSUE TITLE
アプリのPWA化

### ISSUE THREAD

**Issue by hengin-eer** [hengin-eer/bocchi-talk#6]
- フロントエンドの実装後で良い。優先順位は低め
- `next-pwa`というモジュールを使用する
- `next.config.js`でキャッシュの設定を行う
- `manifest.json`を追加し、Headに追加する
- 参考: https://dev.classmethod.jp/articles/next-js-pwa/

**Comment by QwerTayu** [comment]
実装完了

**Comment by QwerTayu** [comment]
実装完了
