### ISSUE TITLE
feat: デフォルトのメッセージをセットする

### ISSUE THREAD

**Issue by QwerTayu** [hengin-eer/bocchi-talk#75]
### 要望の概要

チャット開始時にユーザからではなくてChatGPTからチャットを開始する

### 要望の動機

空から話始めるよりも、デフォルトのやつがあったほうが英会話っぽい

### 要望の提案

- [x] 白紙からチャットを進めるよりもベースのメッセージを表示させたほうが良さそう
```
Hello! What would you like to talk about today?
Recommend:
- Food
- Sports
- Sightseeing
- country
```

**Comment by QwerTayu** [comment]
-  ロールプレイ
  - フライトにチェックインする
  - ホテルにチェックインする
  - etc...
- ディスカッション
  - ユーザに記入させる
- フリートーク

**Comment by hengin-eer** [comment]
完了によりClose
