### ISSUE TITLE
[release]:リリース準備

### ISSUE THREAD

**Issue by QwerTayu** [hengin-eer/bocchi-talk#95]
### タスク

- [x] リファクタリング
  - [x] 使用していないライブラリの `import` 文を削除
  - [x] 不要な `console.log` (や `alert` )を削除
- [x] PWA実装してることをユーザに伝えたほうが良い？（やり方とか）
- [x] Google Analyticsのinstall
- [x] ダッシュボードのアイコン位置の変更
- [x] favoriteページも存在はさせておこう

**Comment by hengin-eer** [comment]
確かにPWAインストールの手順解説はどっかに乗っけたいよね
トップページに追加するか、新しくページ作るか…

**Comment by QwerTayu** [comment]
https://zenn.dev/rh820/articles/8af90011c573fe
